{% set name = "uproot4" %}
{% set version = "0.0.27" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uproot4-{{ version }}.tar.gz
  sha256: 694debb6a24445da109bd2bfe14eb59ca1a79681aba839b0591bce803ca4e00c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy
    - python >=3.5

test:
  imports:
    - uproot4
    - uproot4.behaviors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/uproot4
  summary: ROOT I/O in pure Python and NumPy.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
